### ISSUE TITLE
DBの再考慮

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/RNS_project01#4]
RaspberryPiにDB入れること自体がよくなかったっぽいので、
DBに関していろいろ決め直す必要があります。
わからないことばかりだけど、調べながらいい案考えましょう。

**Comment by kakaka19** [comment]
https://www.raspberrypi.org/products/raspberry-pi-3-model-b/

ラズパイのRAMが1GBしかないので、それぞれのPCにテスト用のDBサーバを用意しておくのが、とりあえずの回避策だと思います。環境依存とかで問題が頻繁する可能性はありますが……

**Comment by ikkyu-3** [comment]
> それぞれのPCにテスト用のDBサーバを用意しておくのが、とりあえずの回避策だと思います。  

ではとりあえずテストDBサーバを作成ということにしようと思います。
「elasticsearchをローカルにインストールする」で行きましょう！

> 環境依存とかで問題が頻繁する可能性はありますが……

ポート番号を一緒にするぐらいでいいですかね？

**Comment by kakaka19** [comment]
起動オプションでポート指定できるので、起動用のシェルスクリプトとか用意しとけば問題ないかなと思います。

**Comment by ikkyu-3** [comment]
了解。シェルスクリプトで対応します。

といいつつ、作成したことないので、
作成がてら、シェルスクリプトの作成方法を共有したいと思います。
新しくissueつくります。

ということで対応が決まったので、closeします。
